# Generated by Django 3.1 on 2020-09-03 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddMainTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicname', models.CharField(max_length=10000)),
                ('topictype', models.CharField(max_length=10000)),
                ('description', models.TextField(max_length=10000)),
                ('syntax', models.TextField(max_length=10000)),
                ('example', models.TextField(max_length=10000)),
                ('output', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='C:\\Users\\A560918\\OneDrive - AF\\Desktop\\Programming\\static\\tutorial/private_images/')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutorial.addmaintopic')),
            ],
        ),
        migrations.CreateModel(
            name='AddSubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicname', models.CharField(max_length=10000)),
                ('topictype', models.CharField(max_length=10000)),
                ('description', models.TextField(max_length=10000)),
                ('syntax', models.TextField(max_length=10000)),
                ('example', models.TextField(max_length=10000)),
                ('output', models.TextField(max_length=10000)),
                ('maintopic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutorial.addmaintopic')),
            ],
        ),
    ]
