# Generated by Django 3.1 on 2020-09-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_addmaintopic_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmaintopic',
            name='language',
            field=models.CharField(max_length=10000),
        ),
    ]
